name: Exoplanet Scouter GraphQL API

on:
  push:
        branches:
            - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
          - uses: actions/checkout@v2

          - name: Code validation
            run: |
                yarn install
                yarn test

          - name: Build docker image
            run: |
                docker build --file Dockerfile.prod -t exoscout .
                docker save -o exoscout-image exoscout

          - name: Transfer docker image 
            uses: appleboy/scp-action@master
            with:
                host: ${{ secrets.HOSTNAME }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                source: exoscout-image
                target: exoplanet-scouter

          - name: Prepare service
            uses: appleboy/ssh-action@master
            with:
                host: ${{ secrets.HOSTNAME }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.KEY }}
                script: |
                    docker load -i exoplanet-scouter/exoscout-image
                    docker-compose up --build -d
